import Head from "next/head";
import RecipeList from "../components/RecipeList";

export default function Home({ recipes }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {console.log(recipes)}
      <RecipeList recipes={recipes} />
    </div>
  );
}

//Fetch api
export const getStaticProps = async () => {
  const res = await fetch(
    `https://api.spoonacular.com/recipes/complexSearch?apiKey=${process.env.NEXT_APP_API_KEY}`
  );
  const recipes = await res.json();

  return {
    props: {
      recipes,
    },
  };
};
